---
- name: Configure network devices 
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
  tasks: 
    - name: Configure interface FastEthernet 
      ios_command:
        commands:
          - conf t
          - interface FastEthernet1/0
          - ip address 192.168.61.142 255.255.255.0
          - no shutdown
          - interface FastEthernet2/0
          - ip address 192.168.62.152 255.255.255.0
          - no shutdown
          - interface FastEthernet3/0
          - ip address 192.168.60.200 255.255.255.0
          - no shutdown
      register: result_fastethernet
      register: result_interface_config
    - name: Configure OSPF
      ios_command:
        commands:
          - conf t
          - router ospf 1
          - network 0.0.0.0 255.255.255.255 area 0
      register: result_ospf

    - name: save
      ios_command:
        commands:
          - wr


    - name: Print task results
      debug:
        var: item
      with_items:
        - result_interface_config
        - result_ospf
